-- CREATE TABLE
--     IF NOT EXISTS job_events (
--         event_id UUID,
--         job_id UUID,
--         job_type String,
--         from_status LowCardinality (String),
--         to_status LowCardinality (String),
--         worker_id String,
--         duration_ms Int64,
--         error_msg String DEFAULT '',
--         occurred_at DateTime64 (3)
--     ) ENGINE = MergeTree ()
-- ORDER BY
--     (occurred_at, job_type)
-- PARTITION BY
--     toYYYYMM (occurred_at);